name: smart_attendance
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  gsheets: any
  intl: 0.17.0
  geolocator: 9.0.2
  animated_splash_screen: any
  google_fonts: any
  animated_text_kit: 4.2.2
  provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
